/** @format */

import {DynamicFormJsonSchema} from '../models/dynamic-form-json-schema.model';

export const ALL_COMPONENTS_JSON_SCHEMA: DynamicFormJsonSchema = {
   id: 'all-components-json-test',
   groups: [
      {
         id: 'base',
         title: 'JSON - Componenti base',
         class: ['col-12', 'p-0'],
         fields: [
            {
               name: 'jsonInfo',
               type: 'LABEL',
               title: 'Form JSON',
               class: ['col-12'],
               value: 'Configurazione JSON pura: niente FormControl, niente Validators Angular, niente funzioni dentro il JSON.',
            },
            {name: 'separatorBase', type: 'SEPARATOR', title: 'Dati anagrafici', class: ['col-12']},
            {
               name: 'firstName',
               type: 'TEXT',
               title: 'Nome',
               class: ['col-12', 'col-md-6'],
               props: {placeholder: 'Inserisci il nome'},
               validators: [{type: 'required'}, {type: 'minLength', value: 3}],
               events: {change: 'logFieldChange'},
            },
            {
               name: 'lastName',
               type: 'TEXT',
               title: 'Cognome',
               class: ['col-12', 'col-md-6'],
               props: {placeholder: 'Inserisci il cognome'},
               validators: [{type: 'required'}],
            },
            {
               name: 'email',
               type: 'EMAIL',
               title: 'Email',
               class: ['col-12', 'col-md-6'],
               props: {placeholder: 'nome@email.it'},
               validators: [{type: 'required'}, {type: 'email'}],
            },
            {
               name: 'description',
               type: 'TEXTAREA',
               title: 'Descrizione',
               class: ['col-12', 'col-md-6'],
               css: {class: ['col-12', 'col-md-6'], rows: 4},
               props: {placeholder: 'Descrizione'},
               validators: [{type: 'maxLength', value: 500}],
            },
         ],
      },
      {
         id: 'dates',
         title: 'JSON - Numeri e date',
         class: ['col-12', 'p-0'],
         fields: [
            {name: 'age', type: 'NUMBER', title: 'Età', class: ['col-12', 'col-md-4'], validators: [{type: 'required'}, {type: 'min', value: 18}], optionNumber: {min: 18, max: 99, step: 1}},
            {name: 'amount', type: 'CURRENCY', title: 'Importo', value: 0, class: ['col-12', 'col-md-4'], validators: [{type: 'required'}, {type: 'min', value: 0}], props: {currency: 'EUR'}},
            {name: 'year', type: 'YEAR', title: 'Anno', value: new Date().getFullYear(), class: ['col-12', 'col-md-4']},
            {name: 'date', type: 'DATA', title: 'Data', class: ['col-12', 'col-md-4'], validators: [{type: 'required'}]},
            {name: 'dateTime', type: 'DATETIME', title: 'Data e ora', class: ['col-12', 'col-md-4']},
            {name: 'time', type: 'TIME', title: 'Ora', value: '09:00', class: ['col-12', 'col-md-4']},
            {name: 'period', type: 'DATARANGE', title: 'Intervallo date', class: ['col-12', 'col-md-6'], readonly: true},
            {name: 'attachment', type: 'FILE', title: 'Allegato', class: ['col-12', 'col-md-6'], props: {accept: '.pdf,.png,.jpg,.jpeg'}},
         ],
      },
      {
         id: 'combo',
         title: 'JSON - Combo e scroll paginato',
         class: ['col-12', 'p-0'],
         fields: [
            {
               name: 'gender',
               type: 'RADIOGROUP',
               title: 'Sesso',
               value: 'M',
               class: ['col-12', 'col-md-6'],
               options: [{id: 'M', description: 'Maschio'}, {id: 'F', description: 'Femmina'}, {id: 'N', description: 'Non specificato'}],
               keyCombo: {keyId: 'id', keyDescription: 'description'},
            },
            {name: 'active', type: 'CHECKBOX', title: 'Attivo', value: true, class: ['col-12', 'col-md-6']},
            {
               name: 'category',
               type: 'COMBO',
               title: 'Categoria',
               class: ['col-12', 'col-md-6'],
               autocomplete: true,
               multiple: false,
               props: {placeholder: 'Scegli categoria', resetButton: true},
               validators: [{type: 'required'}],
               options: [{id: 'travel', description: 'Viaggi'}, {id: 'food', description: 'Alimentari'}, {id: 'medical', description: 'Medico'}, {id: 'sport', description: 'Sport'}, {id: 'home', description: 'Casa'}],
               keyCombo: {keyId: 'id', keyDescription: 'description'},
            },
            {
               name: 'tags',
               type: 'COMBO',
               title: 'Tag multipli',
               class: ['col-12', 'col-md-6'],
               autocomplete: true,
               multiple: true,
               value: [],
               props: {placeholder: 'Seleziona tag', resetButton: true},
               options: [{id: 'urgent', description: 'Urgente'}, {id: 'refund', description: 'Da rimborsare'}, {id: 'private', description: 'Privato'}, {id: 'work', description: 'Lavoro'}],
               keyCombo: {keyId: 'id', keyDescription: 'description'},
            },
            {
               name: 'operatorId',
               type: 'COMBOPAGINATE',
               title: 'Operatore paginato',
               class: ['col-12'],
               autocomplete: true,
               multiple: false,
               props: {placeholder: 'Cerca operatore e scorri in fondo', resetButton: true, scrollThreshold: 48},
               paging: {page: 1, count: 10, totalCount: 75},
               paramsForRemoteData: {tenantId: 1},
               remoteData: 'loadOperatorsPage',
               events: {initialize: 'initOperatorsPage'},
               options: {items: [], totalCount: 75} as any,
               keyCombo: {keyId: 'id', keyDescription: ['description', 'role'], keySearch: 'search'},
            },
         ],
      },
      {
         id: 'misc',
         title: 'JSON - Altro',
         class: ['col-12', 'p-0'],
         fields: [
            {name: 'documentLink', type: 'LINK', title: 'Link documento', class: ['col-12', 'col-md-6'], props: {label: 'Apri example.com', href: 'https://example.com', target: '_blank'}},
            {name: 'sortDirection', type: 'SORTACTION', title: 'Ordinamento', value: 'ASC', class: ['col-12', 'col-md-6'], css: {class: ['col-12', 'col-md-6'], iconCss: 'sort-action-icon', toggleIcons: ['assets/icons/sort-asc.svg', 'assets/icons/sort-desc.svg']}},
            {name: 'notes', type: 'ARRAYSTRING', title: 'Lista note', value: ['Prima nota', 'Seconda nota'], class: ['col-12'], props: {placeholder: 'Aggiungi nota'}},
         ],
         actions: [{label: 'Leggi valori JSON', visible: true, event: 'readGroupValues', cssClassButton: ['btn', 'btn-primary', 'mt-3']}],
      },
   ],
};
